### ISSUE TITLE
Calling /userinfo with expired access_token and valid refresh_token results in 401

### ISSUE THREAD

**Issue by MathiasCiarlo** [oslokommune/gatekeeper#42]
When the access token is expired, but the refresh token is not, user info must be called twice to get user info.

Before first request to /userinfo:
- expired access token
- valid refresh token
Endpoint returns 401 and sets a new access token and refresh token

Before second request to /userinfo:
- valid access token
- valid refresh token
Endpoint returns 200 with user info

What I expected is that gatekeeper first refreshed the tokens, and then fetched the user info, so that only one request is necessary.

**Comment by deifyed** [comment]
I created a small [frontend](https://github.com/deifyed/deleteme) to test this. 

Locally, I could not reproduce the bug. However, when using the Gatekeeper instance in test - I was able to reproduce.

@MathiasCiarlo do you know if the bug exists when doing doing this from a frontend running in test to Gatekeeper in test as well? (just to exclude local -> test problems)
